# PXE Server Configuration
# Generated by configure.py on $timestamp

# Ubuntu version to serve
ubuntu_version: "$ubuntu_version"

# GRUB netboot binary URLs (from Ubuntu package repos)
grub_signed_deb_url: "$grub_signed_deb_url"
grub_modules_deb_url: "$grub_modules_deb_url"

# Target machine configuration (used in autoinstall)
target_username: "$target_username"
target_password_hash: "$target_password_hash"
target_ssh_authorized_keys:
$target_ssh_authorized_keys

# Packages to install on the target machine during autoinstall
target_packages:
$target_packages

# Optional late-commands to run at end of install (before reboot)
target_late_commands:
$target_late_commands
