#!/usr/bin/env python3
"""Prepare a Raspberry Pi SD card as a PXE server.

Works on Linux, macOS, and WSL.
"""

import os
import platform
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import typer
    from rich.console import Console
    from rich.panel import Panel
    from rich.table import Table
except ImportError:
    print("Missing dependencies. Install with:")
    print("  pip install typer rich")
    sys.exit(1)

app = typer.Typer(help="Prepare a Raspberry Pi SD card as a PXE server.")
console = Console()

REPO_DIR = Path(__file__).resolve().parent.parent
CONFIG_DIR = REPO_DIR / "ansible" / "group_vars"


# ==================== Helpers ====================


def generate_password_hash(password: str) -> str:
    """Generate a SHA-512 password hash using the best available method."""
    # Python crypt module (Linux/macOS)
    try:
        import crypt

        return crypt.crypt(password, crypt.mksalt(crypt.METHOD_SHA512))
    except (ImportError, AttributeError):
        pass

    # openssl
    try:
        result = subprocess.run(
            ["openssl", "passwd", "-6", password],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
    except FileNotFoundError:
        pass

    # mkpasswd
    try:
        result = subprocess.run(
            ["mkpasswd", "--method=SHA-512", password],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
    except FileNotFoundError:
        pass

    console.print("[red]No password hashing tool found (need python3 crypt, openssl, or mkpasswd)[/red]")
    raise typer.Exit(1)


def detect_boot_partition() -> Path | None:
    """Auto-detect the Raspberry Pi boot partition."""
    candidates = []

    # macOS
    for name in ["bootfs", "boot"]:
        p = Path(f"/Volumes/{name}")
        if p.exists():
            candidates.append(p)

    # Linux
    user = os.environ.get("USER", "")
    for name in ["bootfs", "boot"]:
        p = Path(f"/media/{user}/{name}")
        if p.exists():
            candidates.append(p)

    # WSL - check common drive letters
    for letter in "defgh":
        p = Path(f"/mnt/{letter}")
        if (p / "config.txt").exists() or (p / "cmdline.txt").exists():
            candidates.append(p)

    for candidate in candidates:
        if (candidate / "config.txt").exists() or (candidate / "cmdline.txt").exists():
            return candidate

    return None


def find_ssh_pubkey() -> str | None:
    """Find the user's SSH public key."""
    ssh_dir = Path.home() / ".ssh"
    for name in ["id_ed25519.pub", "id_rsa.pub", "id_ecdsa.pub"]:
        keyfile = ssh_dir / name
        if keyfile.exists():
            return keyfile.read_text().strip()
    return None


def validate_mac(mac: str) -> str:
    """Validate and normalize a MAC address."""
    mac = mac.strip().lower()
    if re.match(r"^([0-9a-f]{2}:){5}[0-9a-f]{2}$", mac):
        return mac
    if re.match(r"^([0-9a-f]{2}-){5}[0-9a-f]{2}$", mac):
        return mac.replace("-", ":")
    if re.match(r"^[0-9a-f]{12}$", mac):
        return ":".join(mac[i : i + 2] for i in range(0, 12, 2))
    raise typer.BadParameter(f"Invalid MAC address: {mac} (use format aa:bb:cc:dd:ee:ff)")


def is_boot_partition(path: Path) -> bool:
    """Check if a path looks like a Raspberry Pi boot partition."""
    return (path / "config.txt").exists() or (path / "cmdline.txt").exists()


def write_config(
    pxe_ip: str,
    target_hostname: str,
    target_username: str,
    password_hash: str,
    target_mac: str,
    ssh_key: str,
) -> Path:
    """Generate ansible/group_vars/all.yml."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    config_path = CONFIG_DIR / "all.yml"
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    config_path.write_text(f"""# Generated by prepare_sd.py on {timestamp}

pxe_server_ip: "{pxe_ip}"

ubuntu_version: "24.04.2"

grub_signed_deb_url: "http://archive.ubuntu.com/ubuntu/pool/main/g/grub2-signed/grub-efi-amd64-signed_1.202+2.12-1ubuntu7_amd64.deb"
grub_modules_deb_url: "http://archive.ubuntu.com/ubuntu/pool/main/g/grub2-unsigned/grub-efi-amd64-bin_2.12-1ubuntu7_amd64.deb"

pxe_clients:
  - mac: "{target_mac}"
    name: "{target_hostname}"

target_hostname: "{target_hostname}"
target_username: "{target_username}"
target_password_hash: "{password_hash}"
target_ssh_authorized_keys:
  - "{ssh_key}"

target_packages:
  - curl
  - git
  - ansible
  - jq

target_late_commands: []
""")
    return config_path


def copy_to_sd(boot_mount: Path) -> None:
    """Copy repo files and firstboot service to the SD card."""
    sd_repo = boot_mount / "pxe-homelab"

    # Clean previous copy if exists
    if sd_repo.exists():
        shutil.rmtree(sd_repo)

    # Copy repo contents (excluding .git and large files)
    sd_repo.mkdir()
    for item in ["ansible", "scripts"]:
        shutil.copytree(REPO_DIR / item, sd_repo / item)
    for item in ["README.md", ".gitignore"]:
        src = REPO_DIR / item
        if src.exists():
            shutil.copy2(src, sd_repo / item)

    # Copy firstboot script and service to boot root
    firstboot_sh = REPO_DIR / "scripts" / "firstboot.sh"
    firstboot_svc = REPO_DIR / "scripts" / "pxe-firstboot.service"
    shutil.copy2(firstboot_sh, boot_mount / "pxe-firstboot.sh")
    os.chmod(boot_mount / "pxe-firstboot.sh", 0o755)
    shutil.copy2(firstboot_svc, boot_mount / "pxe-firstboot.service")

    # Hook into Pi Imager's firstrun.sh
    firstrun = boot_mount / "firstrun.sh"
    if firstrun.exists():
        content = firstrun.read_text()
        content = content.replace("exit 0\n", "").rstrip()
        content += """

# Enable PXE firstboot service
cp /boot/firmware/pxe-firstboot.service /etc/systemd/system/pxe-firstboot.service 2>/dev/null || \\
cp /boot/pxe-firstboot.service /etc/systemd/system/pxe-firstboot.service 2>/dev/null
systemctl enable pxe-firstboot.service

exit 0
"""
        firstrun.write_text(content)
    else:
        console.print(
            "[yellow]WARNING:[/yellow] No firstrun.sh found (did you configure the Pi in the Imager?).\n"
            "After booting, manually run:\n"
            "  sudo cp /boot/firmware/pxe-firstboot.service /etc/systemd/system/\n"
            "  sudo systemctl enable --now pxe-firstboot.service"
        )


# ==================== Commands ====================


@app.command()
def prepare(
    boot_path: str = typer.Argument(None, help="Path to the Pi boot partition. Auto-detects if omitted."),
    pxe_ip: str = typer.Option(None, "--pxe-ip", help="PXE server (Pi) IP address"),
    hostname: str = typer.Option(None, "--hostname", help="Target machine hostname"),
    username: str = typer.Option(None, "--username", help="Target machine username"),
    mac: str = typer.Option(None, "--mac", help="Target machine MAC address"),
    ssh_key: str = typer.Option(None, "--ssh-key", help="SSH public key (or path to .pub file)"),
    non_interactive: bool = typer.Option(False, "--yes", "-y", help="Skip confirmations"),
):
    """Prepare a Raspberry Pi SD card as a PXE server."""

    console.print(Panel("PXE Homelab - SD Card Preparation", style="bold blue"))

    # ---- Boot partition ----
    if boot_path:
        boot_mount = Path(boot_path)
    else:
        console.print("Searching for boot partition...")
        detected = detect_boot_partition()
        if detected:
            console.print(f"Found: [cyan]{detected}[/cyan]")
            if non_interactive or typer.confirm("Use this?", default=True):
                boot_mount = detected
            else:
                boot_path = typer.prompt("Enter path to boot partition")
                boot_mount = Path(boot_path)
        else:
            console.print("[yellow]Could not auto-detect boot partition.[/yellow]")
            console.print("  macOS:  usually /Volumes/bootfs")
            console.print("  Linux:  usually /media/$USER/bootfs")
            console.print("  WSL:    usually /mnt/d or /mnt/e")
            boot_path = typer.prompt("Enter path to boot partition")
            boot_mount = Path(boot_path)

    if not is_boot_partition(boot_mount):
        console.print(f"[red]ERROR:[/red] {boot_mount} doesn't look like a Raspberry Pi boot partition")
        console.print("       (no config.txt or cmdline.txt found)")
        raise typer.Exit(1)

    # ---- PXE server IP ----
    if not pxe_ip:
        pxe_ip = typer.prompt("PXE server (Pi) IP address")

    # ---- Target machine config ----
    console.print("\n[bold]Target Machine Configuration[/bold]")

    if not hostname:
        hostname = typer.prompt("Hostname")

    if not username:
        username = typer.prompt("Username")

    password = typer.prompt("Password", hide_input=True, confirmation_prompt=True)

    if not mac:
        mac = typer.prompt("MAC address (aa:bb:cc:dd:ee:ff)")
    mac = validate_mac(mac)

    # ---- SSH key ----
    if not ssh_key:
        found_key = find_ssh_pubkey()
        if found_key:
            key_preview = found_key[:60] + "..." if len(found_key) > 60 else found_key
            console.print(f"\nFound SSH key: [dim]{key_preview}[/dim]")
            if non_interactive or typer.confirm("Use this key?", default=True):
                ssh_key = found_key

        if not ssh_key:
            ssh_key_input = typer.prompt("SSH public key (paste key or path to .pub file)")
            key_path = Path(ssh_key_input).expanduser()
            if key_path.exists():
                ssh_key = key_path.read_text().strip()
            else:
                ssh_key = ssh_key_input.strip()

    # ---- Generate password hash ----
    console.print("\nGenerating password hash...")
    password_hash = generate_password_hash(password)

    # ---- Generate config ----
    console.print("Creating configuration...")
    config_path = write_config(
        pxe_ip=pxe_ip,
        target_hostname=hostname,
        target_username=username,
        password_hash=password_hash,
        target_mac=mac,
        ssh_key=ssh_key,
    )
    console.print(f"  Config written to: [dim]{config_path}[/dim]")

    # ---- Copy to SD card ----
    console.print("Copying files to SD card...")
    copy_to_sd(boot_mount)

    # ---- Summary ----
    table = Table(title="Configuration Summary", show_header=False)
    table.add_column("Key", style="cyan")
    table.add_column("Value", style="white")
    table.add_row("PXE Server IP", pxe_ip)
    table.add_row("Target Hostname", hostname)
    table.add_row("Target Username", username)
    table.add_row("Target MAC", mac)
    table.add_row("SSH Key", ssh_key[:50] + "..." if len(ssh_key) > 50 else ssh_key)
    table.add_row("Boot Partition", str(boot_mount))
    console.print()
    console.print(table)

    console.print(Panel(
        "[bold green]SD Card Ready![/bold green]\n\n"
        "Next steps:\n"
        "  1. Eject the SD card\n"
        "  2. Insert into Pi and power on (connect ethernet first)\n"
        f"  3. Wait for setup to complete (~30 min, mostly ISO download)\n"
        f"  4. Monitor: [cyan]ssh <pi-user>@{pxe_ip} 'journalctl -u pxe-firstboot -f'[/cyan]\n"
        "  5. PXE boot the target machine",
        title="Done",
    ))


if __name__ == "__main__":
    app()
