# Update ansible_host with your Pi's IP address
# Update ansible_user with the username you set in Pi Imager
all:
  hosts:
    pxe-server:
      ansible_host: <pxe-server-ip>
      ansible_user: <pi-username>
